#pragma once

struct LanguageEntry {
  const char *source;
  const char *translation;
};

// Common web labels are translated centrally so all generated pages use the
// same terminology. German remains the source language and default build.
static const LanguageEntry LANGUAGE_ENTRIES[] = {
  {"Fuellstandsmesser3", "Level Meter 3"},
  {"Füllstand aktuell", "Current level"},
  {"Füllstand & Verbrauch", "Level & consumption"},
  {"Füllstand", "Level"},
  {"Füllhöhe", "Fill height"},
  {"Sensorabstand", "Sensor distance"},
  {"Tankfaktor", "Tank factor"},
  {"Verbrauch", "Consumption"},
  {"Nachfüllung", "Refill"},
  {"Nachfuellung", "Refill"},
  {"Nachfüllereignisse", "Refill events"},
  {"Status", "Status"},
  {"Systemstatus", "System status"},
  {"System / Wartung", "System / maintenance"},
  {"Einstellungen", "Settings"},
  {"Kalibrierung", "Calibration"},
  {"Kalibrier-Assistent", "Calibration assistant"},
  {"Historie", "History"},
  {"Historie importieren", "Import history"},
  {"Dashboard", "Dashboard"},
  {"WLAN", "Wi-Fi"},
  {"verbunden", "connected"},
  {"getrennt", "disconnected"},
  {"MQTT aktivieren", "Enable MQTT"},
  {"MQTT", "MQTT"},
  {"ToF", "ToF"},
  {"BME280", "BME280"},
  {"Temperatur", "Temperature"},
  {"Feuchte", "Humidity"},
  {"Taupunkt", "Dew point"},
  {"Datum", "Date"},
  {"Uhrzeit", "Time"},
  {"Firmware", "Firmware"},
  {"Gerät", "Device"},
  {"Uptime", "Uptime"},
  {"System-Health", "System health"},
  {"Heap frei", "Free heap"},
  {"Heap Minimum", "Minimum heap"},
  {"Historiedaten", "History data"},
  {"Testdaten", "Test data"},
  {"Wartungsaktionen", "Maintenance actions"},
  {"Speichern", "Save"},
  {"Zurück", "Back"},
  {"Bereit", "Ready"},
  {"Fehler", "Error"},
  {"Warnung", "Warning"},
  {"AUS", "OFF"},
  {"OK", "OK"},
  {"Automatisch erkennen", "Detect automatically"},
  {"Zylinder", "Cylinder"},
  {"Quader", "Rectangular tank"},
  {"Medianfilter verwenden", "Use median filter"},
  {"OLED verwenden", "Use OLED"},
  {"NTP verwenden", "Use NTP"},
  {"Keine gültige aktuelle Sensor-Messung verfügbar.", "No valid current sensor measurement available."},
  {"Unbekannter Referenzpunkt.", "Unknown reference point."},
  {"Kein Liter-Referenzwert angegeben.", "No litre reference value provided."},
  {"Werte", "Values"},
  {nullptr, nullptr}
};
